; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=mips64el-scei-ps2 -mcpu=r5900 -relocation-model=static -verify-machineinstrs < %s | FileCheck %s --check-prefix=N32
; RUN: llc -mtriple=mipsel-unknown-linux-gnu -mcpu=mips32 -mattr=+single-float -relocation-model=static -verify-machineinstrs < %s | FileCheck %s --check-prefix=O32

; N32 single-float targets have 64-bit ABI GPRs. A callee must preserve all
; 64 bits even when register allocation only needs the 32-bit subregister.
; O32 single-float targets continue to preserve 32-bit GPRs.

define signext i32 @callee_saved_gpr(i32 signext %count) {
entry:
  %has.iterations = icmp sgt i32 %count, 0
  br i1 %has.iterations, label %loop, label %exit

loop:
  %index = phi i32 [ 0, %entry ], [ %next.index, %loop ]
  %total = phi i32 [ 0, %entry ], [ %next.total, %loop ]
  %value = call signext i32 @opaque(i32 signext %index)
  %next.total = add nsw i32 %value, %total
  %next.index = add nuw nsw i32 %index, 1
  %finished = icmp eq i32 %next.index, %count
  br i1 %finished, label %exit, label %loop

exit:
  %result = phi i32 [ 0, %entry ], [ %next.total, %loop ]
  ret i32 %result
}

declare signext i32 @opaque(i32 signext)

define void @clobber_all_callee_saved_gprs() {
entry:
  call void asm sideeffect "", "~{$16},~{$17},~{$18},~{$19},~{$20},~{$21},~{$22},~{$23},~{$28},~{$30},~{$1}"()
  ret void
}

; N32-LABEL: callee_saved_gpr:
; N32:       # %bb.0:
; N32:         addiu $sp, $sp, -32
; N32:         sd $ra, 24($sp)
; N32-NEXT:    sd $18, 16($sp)
; N32-NEXT:    sd $17, 8($sp)
; N32-NEXT:    sd $16, 0($sp)
; N32:         ld $16, 0($sp)
; N32-NEXT:    ld $17, 8($sp)
; N32-NEXT:    ld $18, 16($sp)
; N32-NEXT:    ld $ra, 24($sp)
; N32-NEXT:    jr $ra

; O32-LABEL: callee_saved_gpr:
; O32:       # %bb.0:
; O32:         addiu $sp, $sp, -32
; O32:         sw $ra, 28($sp)
; O32-NEXT:    sw $18, 24($sp)
; O32-NEXT:    sw $17, 20($sp)
; O32-NEXT:    sw $16, 16($sp)
; O32:         lw $16, 16($sp)
; O32-NEXT:    lw $17, 20($sp)
; O32-NEXT:    lw $18, 24($sp)
; O32-NEXT:    lw $ra, 28($sp)
; O32-NEXT:    jr $ra

; N32-LABEL: clobber_all_callee_saved_gprs:
; N32:         addiu $sp, $sp, -80
; N32:         sd $fp, 72($sp)
; N32-NEXT:    sd $gp, 64($sp)
; N32-NEXT:    sd $23, 56($sp)
; N32-NEXT:    sd $22, 48($sp)
; N32-NEXT:    sd $21, 40($sp)
; N32-NEXT:    sd $20, 32($sp)
; N32-NEXT:    sd $19, 24($sp)
; N32-NEXT:    sd $18, 16($sp)
; N32-NEXT:    sd $17, 8($sp)
; N32-NEXT:    sd $16, 0($sp)
; N32:         ld $16, 0($sp)
; N32-NEXT:    ld $17, 8($sp)
; N32-NEXT:    ld $18, 16($sp)
; N32-NEXT:    ld $19, 24($sp)
; N32-NEXT:    ld $20, 32($sp)
; N32-NEXT:    ld $21, 40($sp)
; N32-NEXT:    ld $22, 48($sp)
; N32-NEXT:    ld $23, 56($sp)
; N32-NEXT:    ld $gp, 64($sp)
; N32-NEXT:    ld $fp, 72($sp)

; O32-LABEL: clobber_all_callee_saved_gprs:
; O32:         addiu $sp, $sp, -40
; O32:         sw $fp, 36($sp)
; O32-NEXT:    sw $23, 32($sp)
; O32-NEXT:    sw $22, 28($sp)
; O32-NEXT:    sw $21, 24($sp)
; O32-NEXT:    sw $20, 20($sp)
; O32-NEXT:    sw $19, 16($sp)
; O32-NEXT:    sw $18, 12($sp)
; O32-NEXT:    sw $17, 8($sp)
; O32-NEXT:    sw $16, 4($sp)
; O32:         lw $16, 4($sp)
; O32-NEXT:    lw $17, 8($sp)
; O32-NEXT:    lw $18, 12($sp)
; O32-NEXT:    lw $19, 16($sp)
; O32-NEXT:    lw $20, 20($sp)
; O32-NEXT:    lw $21, 24($sp)
; O32-NEXT:    lw $22, 28($sp)
; O32-NEXT:    lw $23, 32($sp)
; O32-NEXT:    lw $fp, 36($sp)
